# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/developorg.gradle.jvmargs=-Xmx2G
# 1.21.x Requires Java 21+!
minecraft_version=1.21.8
yarn_mappings=1.21.8+build.1
loader_version=0.16.10

# Mod Properties
mod_version=1.0.0
maven_group=com.teoe.wdl
archives_base_name=wdl-fabric

# Dependencies
fabric_version=0.136.1+1.21.8